using Banking.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Banking.Views
{
	/// <summary>
	/// Interaction logic for OverviewWindow.xaml
	/// </summary>
	public partial class OverviewWindow : Window
	{
		OverviewViewModel OverviewMV { get; set; }

		public OverviewWindow(MainViewModel mainMV)
		{
			InitializeComponent();

			OverviewMV = new OverviewViewModel(this, mainMV);
			OverviewsComboBox.ItemsSource = OverviewMV.Overviews;
			OverviewsComboBox.SelectedIndex = (int)OverviewViewModel.OverviewItem.CommonlyExpenses;

			_ = ShowDialog();
		}

		private void OverviewsComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			OverviewViewModel.OverviewItem selectedOverview = (OverviewViewModel.OverviewItem)((ComboBox)sender).SelectedIndex;
			OverviewMV.SelectOverview(selectedOverview);
		}

		private void PivotDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{

			for (int i = 1; i < PivotDataGrid.Columns.Count; i++)
			{
				PivotDataGrid.Columns[i].MinWidth = 60;
			}

		}

		private void PivotDataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
		{
			//var Col = (string)((DataGrid)sender).CurrentCell.Column.Header;
			//var Row = (string)((DataRowView)((DataGrid)sender).CurrentCell.Item).Row.ItemArray[0];

			OverviewMV.FilterAccountList(
				(string)((DataGrid)sender).CurrentCell.Column.Header,
				(string)((DataRowView)((DataGrid)sender).CurrentCell.Item).Row.ItemArray[0]
				);

		}

		private void ExportButton_Click(object sender, RoutedEventArgs e)
		{
			OverviewMV.ExportPivot();
		}
	}
}
